style changes
zeitgeistpm/documentation pull request #47
Opened 2022-06-16 18:38 UTC by robhyrk

2022-06-17 12:18 UTC, maltekliemann commented
Closed #39.

2022-06-17 12:53 UTC, maltekliemann requested changes
Hey @robhyrk! Again, many thanks for prettifying our site. Looks gorgeous! 💯 

I'm sure that you'll receive the new assets very soon and can start making the required changed. Other than that, I've noticed a couple of small things.

- The sidebar on the left get's cut off when scrolling down. This happens on the Polkadot wiki, as well, so I wouldn't be surprised if there's no immediate fix for this.
  <img width="1920" alt="Screenshot 2022-06-17 at 14 49 01" src="https://user-images.githubusercontent.com/49552287/174301704-ee1b6a60-9d5a-4140-ad08-0323e9f12d01.png">

- Outside of the launch page, the Zeitgeist logo doesn't render correctly:
  <img width="1920" alt="Screenshot 2022-06-17 at 14 24 22" src="https://user-images.githubusercontent.com/49552287/174301923-7e2f892f-f434-4af1-8154-789a035be554.png">

- The social media icons don't show anywhere. Seemed to be working yesterday. :shrug:

2022-06-17 12:53 UTC, maltekliemann commented on src/components/HomepageFeatures/index.tsx
> +            <p>This wiki was started by and is maintained by Web3 Foundation. It is an open-source-ish project and aims to be the most extensive resource of knowledge on Polkadot and the Polkadot eco
```suggestion
            <h2>Help improve the Zeitgeist documentation</h2>
            <p>The Zeitgeist documentation is an open-source project maintainted by Zeitgeist PM and continuously improved by the Zeitgeist community.</p>
```

2022-07-06 18:20 UTC, robhyrk commented
@maltekliemann thanks for the feedback. 

I couldn't replicate the scrolling issue so hopefully that got resolved when I updated the docs with the new assets; otherwise it might be an issue with Docusaraus as you mentioned the Polkdadot site also has it.

Logo in the footer should be fixed now too...was just missing a '/' when pointing to the asset.

Largest update was incorporating all the new design changes so it should look nice and sleek now.

2022-07-07 09:08 UTC, maltekliemann approved these changes
Looks good to me!

2022-07-07 15:51 UTC, merged