Upgrade for zeitgeistpm/sdk-v0.6.5
zeitgeistpm/documentation pull request #56
Opened 2022-08-04 04:57 UTC by saboonikhil

- Add links to argument types
- Update code snippets
- Sync with latest sdk changes

2022-08-04 11:12 UTC, maltekliemann requested changes
Although it would technically work to use `10` as swap fee, this doesn't seem like a realistic value. It should probably be `1_000_000_000` or `100_000_000`.

Other than that, two general comments:

- The indentation is inconsisent throughout the SDK documentation. Sometimes it's two spaces per indent, sometimes four.
- I think these examples would be easier to read if all numbers used a thousands separator, i.e. `10_000_000_000` instead of `10000000000`.

Also, would it be possible to define a `BASE` object in the SDK that people can use? It seems very timesome and frankly very error-prone to keep using explicit numbers.

2022-08-04 11:12 UTC, maltekliemann commented on docs/build/sdk/indexs.md
> +  swapFee: `10`,
If you use `10`, then you've a swap fee of `1e-09` percent, which is probably not what you want.

```suggestion
  swapFee: `1_000_000_000`,
```

2022-08-04 11:12 UTC, maltekliemann commented on docs/build/sdk/market.md
> +    `10`,
If you use `10`, then you've a swap fee of `1e-09` percent, which is probably not what you want.

```suggestion
    `1_000_000_000`,
```

2022-08-04 14:17 UTC, saboonikhil commented
> Although it would technically work to use `10` as swap fee, this doesn't seem like a realistic value. It should probably be `1_000_000_000` or `100_000_000`.
> 
> Other than that, two general comments:
> 
> * The indentation is inconsisent throughout the SDK documentation. Sometimes it's two spaces per indent, sometimes four.
> * I think these examples would be easier to read if all numbers used a thousands separator, i.e. `10_000_000_000` instead of `10000000000`.
> 
> Also, would it be possible to define a `BASE` object in the SDK that people can use? It seems very timesome and frankly very error-prone to keep using explicit numbers.

I don't think the typescript data type `string` allows much.

We can work on the `BASE` object post discussion with the frontend team.

- If thousands separator is used, the error is thrown : `Struct: failed on swap_fee: Compact<u128>:: Invalid character`
- If `10,000,000,000` is used, the error looks like : `Struct: failed on swap_fee: Compact<u128>:: String should not contain decimal points or scientific notation`
- If `10` is used as `swapFee`, the pool is created with following properties:
<img width="508" alt="Screenshot 2022-08-04 at 7 30 13 PM" src="https://user-images.githubusercontent.com/36529278/182867828-88f54dcf-7d25-4636-a5a4-212ad023e1f6.png">

2022-08-04 14:24 UTC, maltekliemann commented
Nevertheless, I would not use `10` as swap fee (for instructive purposes).

Regarding the thousands separators, why are you guys using strings to communicate with polkadot-js?

2022-08-04 14:59 UTC, saboonikhil commented
> 

What value would you recommend as an example for `swapFee`?

String? Just to keep it consistent with the [polkadot-js apps](https://polkadot.js.org/apps). They don't support thousands separators. Probably, another reason why it could potentially add to the confusion when combining using the SDK with just the usual polkadot-js api, as you'll end up with 2 different units there.

2022-08-04 15:45 UTC, maltekliemann commented
I would expect numbers to be numbers and not strings, and so on. I would find it quite bothersome if I had to convert numbers to strings everytime I do an SDK call. Did I get this right, this is a restriction imposed by polkadot-js?

2022-08-04 21:17 UTC, maltekliemann approved these changes
:thumbsup:

2022-08-05 03:21 UTC, saboonikhil commented
Thank you very much!

2022-08-05 03:22 UTC, merged