Update the introduction to the SDK
zeitgeistpm/documentation pull request #71
Opened 2022-09-16 19:35 UTC by LiamDotPro

Adds some extra information about where to find the SDK source files and also how to easily add it to you're own javascript based product.

2022-09-17 10:16 UTC, maltekliemann requested changes
Thanks for contributing!

2022-09-17 10:16 UTC, maltekliemann commented on docs/build/sdk/introduction.md
> +`npm i @zeitgeistpm/sdk` or `yarn add @zeitgeistpm/sdk`
~~~suggestion
The Zeitgeist SDK is written in `Typescript` and can be found here:
[@zeitgeistpm/sdk](https://github.com/zeitgeistpm/tools/tree/main/packages/sdk).
You can do the following to install it directly into your javascript based
project:

```
npm i @zeitgeistpm/sdk` or `yarn add @zeitgeistpm/sdk
```
~~~

2022-09-19 14:32 UTC, maltekliemann requested changes

2022-09-19 14:32 UTC, maltekliemann commented on docs/build/sdk/introduction.md
> +```
Sorry, I'm dumb 🤦‍♂️. Didn't see the _or_ in there.

```suggestion
project: `npm i @zeitgeistpm/sdk` or `yarn add @zeitgeistpm/sdk`.

2022-09-26 12:55 UTC, LiamDotPro commented
@maltekliemann Updated

2022-09-26 13:23 UTC, maltekliemann approved these changes

2022-09-26 13:32 UTC, merged