Add notes about disputes
zeitgeistpm/documentation pull request #75
Opened 2022-12-18 13:04 UTC by maltekliemann

Just getting the ball rolling on getting the docs up to speed.

2023-10-29 16:41 UTC, maltekliemann commented
@Chralt98 Can you take a quick peek at this and tell me if this is still required or if there's any overlap?

2023-11-01 10:08 UTC, Chralt98 requested changes

2023-11-01 10:08 UTC, Chralt98 commented on docs/learn/using-zeitgeist-markets.md
> +bond_ and report the outcome they believe to be correct (the _suggestion_).
```suggestion
bond_.
```

2023-11-01 10:08 UTC, Chralt98 commented on docs/learn/using-zeitgeist-markets.md
> +during market creation. The currently available dispute mechanisms are:
```suggestion
How the dispute is resolved depends on the [decentralized court] _dispute mechanism_.
```

2023-11-01 10:08 UTC, Chralt98 commented on docs/learn/using-zeitgeist-markets.md
> +  which is then used as the resolved outcome.
```suggestion
In short: A group of randomly selected jurors vote secretly to find a [Schelling point] among the market's outcomes, which is then used as the resolved outcome.
```

2023-11-01 10:08 UTC, Chralt98 commented on docs/learn/using-zeitgeist-markets.md
> +to the disputant. If this is not the case, the dispute bond is slashed.
```suggestion
to the disputant. If this is not the case, the dispute bond is slashed.
More on that in the bonds section of the [Using Zeitgeist Markets] page.
```

2023-11-01 10:08 UTC, Chralt98 commented on docs/learn/using-zeitgeist-markets.md
> +[schelling point]: https://en.wikipedia.org/wiki/Focal_point_(game_theory)
```suggestion
[schelling point]: https://en.wikipedia.org/wiki/Focal_point_(game_theory)
[Using Zeitgeist Markets]: ./using-zeitgeist-markets
```

2023-11-01 10:09 UTC, Chralt98 commented
I didn't check the non-modified lines of this file. I think if we just mention court as the dispute mechanism we are fine for the future, because why mentioning (soon) deprecated code?

2023-11-13 12:25 UTC, Chralt98 approved these changes

2023-11-14 10:35 UTC, merged